import type { Project } from "@types/index"

// EDIT: mettre à jour les projets avec les vraies images et descriptions
export const projects: Project[] = [
  {
    slug: "juste1cafe",
    title: "Blog SEO juste1cafe.com",
    client: "Projet personnel",
    category: "seo",
    year: 2025,
    tags: ["SEO", "Astro", "Mediavine", "Amazon Associates", "EEAT"],
    description: "Blog café lancé en septembre 2025, 499 clics organiques/mois en 4 mois.",
    results: "+623% trafic organique en 4 mois · Accepté Journey by Mediavine",
    image: "/juste1cafe.png",
    link: "https://juste1cafe.com",
    featured: true,
  },
  {
    slug: "site-onis",
    title: "Création du site vitrine d'ONIS",
    client: "Onis",
    category: "webflow",
    year: 2025,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/onis.png",
    link: "https://be-onis.com",
    featured: true,
  },
  {
    slug: "site-proflamme",
    title: "Création du site vitrine de Proflamme",
    client: "Proflamme",
    category: "webflow",
    year: 2025,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/proflamme.png",
    link: "https://www.proflamme.com",
    featured: false,
  },
  {
    slug: "site-prologis",
    title: "Création du site vitrine de Prologis",
    client: "Prologis",
    category: "webflow",
    year: 2025,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/prologis.png",
    link: "https://www.prologis-eco.com",
    featured: false,
  },
  {
    slug: "site-jerome-cintrat",
    title: "Création du site vitrine pour Jérôme Cintrat",
    client: "Jérôme Cintrat",
    category: "webflow",
    year: 2026,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/jerome.png",
    link: "https://www.charpente-couverture-cintrat.fr",
    featured: true,
  },
  {
    slug: "site-courtier-carrelage",
    title: "Création d'une landing page pour Le courtier du Carrelage",
    client: "Le courtier du carrelage",
    category: "webflow",
    year: 2026,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow", "Google Ads"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/courtier-carrelage.png",
    link: "https://www.lecourtierducarrelage.com",
    featured: false,
  },
  {
    slug: "site-tfn",
    title: "Création du site vitrine de Transport Funéraire de Normandie",
    client: "Transport funéraire de Normandie",
    category: "webflow",
    year: 2025,
    tags: ["Webflow", "GSAP", "GTM", "CMS Webflow", "Google Ads"],
    description: "Site vitrine Webflow avec animations scroll, CMS dynamique et intégrations GTM.",
    image: "/tfn.png",
    featured: false,
  },
]
